import { Aluno } from '../core/models/aluno.model';

export const ALUNOSMOCK: Aluno[] = [
  {
    idaluno: 1,
    nome: 'André',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 2,
    nome: 'Marcio',
    cpf: '987.654.321-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 3,
    nome: 'João',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 4,
    nome: 'Maria',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
  {
    idaluno: 5,
    nome: 'Cleber',
    cpf: '123.456.789-00',
    status: true,
    datacriacao: new Date(),
    dataalteracao: new Date(),
    usucriacao: 'admin',
    usualteracao: 'admin',
  },
];